### ISSUE TITLE
你好！有个问题，望指点！

### ISSUE THREAD

**Issue by liuzengwei** [jawidx/web-launch-app#13]
感谢作者能够开源此代码，让我在工作中省去了很多时间。奈何能力有限，在ios中有个小问题不知道咋回事，在 ios 浏览器打开时候 先弹出了 `Safari打不开该网页，因为网址无效` ，然后再进入下载页。
我用的 ios 和 安卓 打开模式都是 **scheme** 
@web-launch-app：”^2.1.9“ 
大致配置如下
`const schemeConfig = {
    android: {
        protocol: 'astroapp://splash_android',
        index: {
            path: '/',
        },
    },
    ios: {
        protocol: 'astro://',
        index: {
            path: '/'
        },
    }
}
const lanchApp = new LaunchApp({
    inApp: inApp,
    appVersion: appVersion,
    pkgName: '',
    deeplink: {
        scheme: schemeConfig
    },
    pkgs: {
        android: 'https://xxx',
        ios: 'https://xxx',
        yyb: '',
    },
    useUniversalLink: supportLink,
    useAppLink: supportLink,
    autodemotion: true,
    useYingyongbao: inWeixin,
    useGuideMethod: inWeixin, // 受限情况下使用引导方案
    landPage: '/'
})`

**Comment by jawidx** [comment]
已经做了兼容，如果还有问题麻烦说下ios及safari版本
