### ISSUE TITLE
微信调用 launchApplication

### ISSUE THREAD

**Issue by wells1013** [jawidx/web-launch-app#2]
微信如何调用 `launchApplication` 这个方法呢？
下面👇这个链接 是得到的h5 微信打开，可以直接调转到app，看了代码 用的方法 是 invoke('launchApplication')  没搞明白 如何调用的。尝试了很久 没有成功。

https://m.igetget.com/hybrid/ebook/detail?bid=3704

**Comment by jawidx** [comment]
这个页面应该不是用的这个库，我了解只有和微信合作的或腾讯自家的才能在微信里直接调起app
