### ISSUE TITLE
download 配置了项目的下载地址, 为什么还是一直跳到好看视频

### ISSUE THREAD

**Issue by x1nGoo** [jawidx/web-launch-app#23]
`     
    const lanchApp = new LaunchApp();

    lanchApp.download({

        pkgs: {

          ios: 'https://itunes.apple.com/cn/app/%E4%BA%9%A6%E9%99%A2/id123123121',

          android: 'http://mytttt.cn/download-page/app/myApp-v3.1.5-release-20191011-170945_2019-10-12_14-04-15_legu_aligned_signed.apk',

          landPage: 'http://mytttt.cn/download-page/'
        }
      })`
1. 配置了项目的下载地址, 为什么还是一直跳到好看视频, 
地址是对的, 原本直接用window.location.href 是可以跳转的
2. 在电脑打开, 点击下载没反应, 不是应该会跳到landPage?

**Comment by jawidx** [comment]
![image](https://user-images.githubusercontent.com/5433378/76717161-d45a3800-676d-11ea-8704-c7b0a483f87b.png)

**Comment by x1nGoo** [comment]
@jawidx 不好意思, 还是没懂什么意思, 是不要pkgs那层结构吗? 我试过去掉了也是不行
![image](https://user-images.githubusercontent.com/20261541/76718392-9d862100-6771-11ea-9d9e-e77f6b3dbd98.png)

**Comment by jawidx** [comment]
const lanchHaokan = new LaunchApp();
    lanchHaokan.download({
        ios: 'https://itunes.apple.com/cn/app/%E4%BA%9%A6%E9%99%A2/id123123121',
        android: 'http://mytttt.cn/download-page/app/myApp-v3.1.5-release-20191011-170945_2019-10-12_14-04-15_legu_aligned_signed.apk',
        landPage: 'http://mytttt.cn/download-page/'
    });

**Comment by jawidx** [comment]
const lanchHaokan = new LaunchApp();
lanchHaokan.download({
ios: 'https://itunes.apple.com/cn/app/%E4%BA%9%A6%E9%99%A2/id123123121',
android: 'http://mytttt.cn/download-page/app/myApp-v3.1.5-release-20191011-170945_2019-10-12_14-04-15_legu_aligned_signed.apk',
landPage: 'http://mytttt.cn/download-page/'
});

**Comment by jawidx** [comment]
const lanchHaokan = new LaunchApp();
lanchHaokan.download({
ios: 'https://itunes.apple.com/cn/app/%E4%BA%9%A6%E9%99%A2/id123123121',
android: 'http://mytttt.cn/download-page/app/myApp-v3.1.5-release-20191011-170945_2019-10-12_14-04-15_legu_aligned_signed.apk',
landPage: 'http://mytttt.cn/download-page/'
});
试了没问题，ios会去appstore，android会下载pkg包（虽然用你的地址没成功），非android、ios平台才会用landpage
