### ISSUE TITLE
link 模式怎么 在微信跳转到APP？

### ISSUE THREAD

**Issue by xushuo** [jawidx/web-launch-app#27]
你好，想问下 link模式配置好之后，总是在微信内部跳转了一个页面地址，但是无法唤起APP。
 
![image](https://user-images.githubusercontent.com/10043177/82799266-5a9ca400-9eac-11ea-8a77-47a8e6e961e0.png)
 
这是我的配置参数

**Comment by xushuo** [comment]
![image](https://user-images.githubusercontent.com/10043177/82799351-815ada80-9eac-11ea-8baf-493c72ad4fba.png)

**Comment by xushuo** [comment]
`	deeplink: {
                     scheme: {
				....
			},
			link: {
				index: {
					url: app.$api.url.bases+'/link/{forumName}'
				}
			},
		 
		},
		launchType: {
			ios: 'link',
			android: 'scheme'
		},
		timeout: 100,
		useUniversalLink: supportLink(),
		useAppLink: supportLink(),
		autodemotion: true,
		useYingyongbao: true,
		useGuideMethod: app.$utils.plateform.isWeixin&&app.$utils.plateform.isAndroid,
`

**Comment by jawidx** [comment]
微信内走应用宝useYingyongbao: inWeixin && isAndroid,
    launchType: {
        ios: inWeixin ? 'store' : 'link',
        android: inWeixin ? 'store' : 'scheme'
    },

**Comment by jawidx** [comment]
微信scheme需要申请或有合作，一般app不用考虑这条路，目前常用方案是微信android走应用宝、ios内走ulink，参见文档中的demo代码
{
    useYingyongbao: inWeixin && isAndroid,
    launchType: {
        ios: inWeixin ? 'store' : 'link',
        android: inWeixin ? 'store' : 'scheme'
    },
}

**Comment by jawidx** [comment]
微信scheme需要申请或有合作，一般app不用考虑这条路，目前常用方案是微信android走应用宝、ios内走ulink，参见文档中的demo代码中的hotLaunch方法

**Comment by jawidx** [comment]
微信ios是支持link的，如果有问题，先确认正常ios link能唤起app，再用chrome ua模拟ios微信看是否正常请求来验证代码中配置，还不行重装两个app再试

**Comment by xushuo** [comment]
> 微信ios是支持link的，如果有问题，先确认正常ios link能唤起app，再用chrome ua模拟ios微信看是否正常请求来验证代码中配置，还不行重装两个app再试

好的，我再试试。目前的效果是点击打开APP之后就会走一个跳转URL的动作，但是走的是自己内部的路由，没办法拉起APP

**Comment by jawidx** [comment]
内部路由....非微信内也不能唤起吧。。。

**Comment by xushuo** [comment]
> 内部路由....非微信内也不能唤起吧。。。

在微信内部打开，但是走的是内部路由，如果把地址粘贴到浏览器，就会出现打开APP的提示。头疼

**Comment by xushuo** [comment]
我这边查看资料可能是跨域的问题。 我的项目地址是 WWW.AAA.COM。通用链接也是这个域名下的，所以一直在内部走的路由，是不是应该是配成WWW.BBB.COM这种地址、、、

**Comment by jawidx** [comment]
可以参考我们的，在好看视频app里分享视频到微信，微信中打开点击里边的内容会走ulink跳转的

**Comment by xushuo** [comment]
换了个域名就通了，多谢老哥的指点。
