### ISSUE TITLE
页面加载执行代码唤起失败，手动触发就成功

### ISSUE THREAD

**Issue by xushuo** [jawidx/web-launch-app#29]
如果把代码写在页面加载时自动触发逻辑里，就会唤起APP失败。
比如VUE的mounted或者里面加一个setTimeOut这种。

但是如果把同样的代码写到按钮，人工手动点击就会成功拉起APP。

想问下又遇到这种情况吗？

**Comment by jawidx** [comment]
浏览器限制 要手动触发，目前没啥解决办法

**Comment by xushuo** [comment]
但是我看京东，咸鱼等通过短信链接点进去，页面加载完会有打开APP的提示。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;jawidx&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月3日(星期五) 凌晨2:17
收件人:&nbsp;&quot;jawidx/web-launch-app&quot;<web-launch-app@noreply.github.com&gt;;
抄送:&nbsp;&quot;xushuo&quot;<893804934@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jawidx/web-launch-app] 页面加载执行代码唤起失败，手动触发就成功 (#29)

**Comment by jawidx** [comment]
我们下载页面有做自动唤起 https://haokan.baidu.com/download?qr=0，是在didmount里timeout唤起，
我们短信用的是htttps://hku.baidu.com/a/xxx，是link(universallink/appink)尝试唤起app，
可以参考

**Comment by xushuo** [comment]
ok，我试试，我看了不同浏览器以及唤起方式也有很大区别。多谢。
