### ISSUE TITLE
较多Android手机的浏览器无法通过iframe唤醒app

### ISSUE THREAD

**Issue by hellolxl** [jawidx/web-launch-app#3]
对于一些特别的手机如三星和oppo等Android浏览器，无法通过iframe唤醒，需要通过location.href等其他方式唤醒。
需特别处理一下这些手机的异常情况，具体可以参考魔窗的js代码：https://static.mlinks.cc/scripts/dist/mlink.min.js

**Comment by jawidx** [comment]
能具体说下你的使用吗，目前scheme方案在android中都是iframe请求，我在oppo上试了可以唤醒
