### ISSUE TITLE
安卓浏览器无法二次唤起app

### ISSUE THREAD

**Issue by xinbloody** [jawidx/web-launch-app#33]
代码如下：
```js
import { LaunchApp } from 'web-launch-app';
const lanchApp = new LaunchApp();
let config = {
        launchType: 'scheme',
        scheme: `...`,
        timeout: 2000
      };
lanchApp.open(config);
```

测试机型：小米MIX2s

系统：miui 11.0.3

浏览器：小米自带浏览器

现象：

点击唤起app后出现引导弹框是否跳转至XXapp，此时如果选择取消，在页面重新点击唤起app，没有再次出现引导弹框。刷新当前页面也无效，必须退出浏览器，重新进入该页面，才可以再次出现引导弹框。

在iframe唤起那里打了log，发现每次点击都进行了src设置，但都只有第一次可以跳转

请问，这是安卓浏览器限制的问题么？还是我的使用不当导致

**Comment by jawidx** [comment]
应该是系统或浏览器做了限制，你可以再确认下
1.此手机小米自带浏览器看别的网站是否有同样问题，
2.此手机上其它浏览器是否有同样问题，
3.其它手机上小米浏览器及其它浏览器是否有同样问题
