### ISSUE TITLE
useGuideMethod=true

### ISSUE THREAD

**Issue by wxtiankong** [jawidx/web-launch-app#35]
此配置无效呢

**Comment by jawidx** [comment]
贴下代码？

**Comment by wxtiankong** [comment]
const haokanConfig = {
    inApp: false,   // TODO
    appVersion: '4.19.5.10',
    pkgName: 'com.baidu.haokan',
    deeplink: {
        scheme: {
            android: schemeConfig,
            ios: schemeConfig
        },
        link: {
            index: { url: 'http://hku.baidu.com/h5/share/homeindex' },
            video: { url: 'http://hku.baidu.com/h5/share/detail' },
            author: { url: 'http://hku.baidu.com/h5/share/detailauthor' }
        }
    },
    pkgs: {
        android: 'https://downpack.baidu.com/baidutieba_AndroidPhone_v8.8.8.6(8.8.8.6)_1020584c.apk',
        ios: 'https://itunes.apple.com/cn/app/id1322948417?mt=8',
        yyb: '',
        store: {
            // other: {
            //     reg: '',
            //     scheme: '',
            //     id: ''
            // },
        }
    },
    useUniversalLink: true,
    useAppLink: supportLink(),
    autodemotion: true,
    useYingyongbao: false,
    useGuideMethod: true,
     guideMethod: () => {
         alert('右上角->在浏览器中打开');
     },
    timeout: 2000,
    landPage: 'https://haokan.baidu.com/download'
};
就是例子，唯一修改不用应用宝，useGuideMethod=true

**Comment by wxtiankong** [comment]
在微信打开

**Comment by wxtiankong** [comment]
已经用其他方案，看你开源试下了有问题，有时间可以修复下可以方便其他人，谢谢

**Comment by jawidx** [comment]
用你贴的配置代码试在android和ios的微信里都试了没问题，除了默认配置，也可以在每次open({useGuideMethod:true})时控制
