### ISSUE TITLE
open的时候callback回调为啥没有调用

### ISSUE THREAD

**Issue by joeky** [jawidx/web-launch-app#46]
// 复杂唤起
      lanchApp.open(
        {
          useYingyongbao: inWeixin && isAndroid,
          launchType: {
            ios: inWeixin ? "store" : "link",
            android: inWeixin ? "store" : "scheme",
          },
          autodemotion: false,
          scheme: "app://path?k=v",
          url: "https://xtaobao.com",
          param: {
            k2: "v2",
          },
          timeout: 2000,
          pkgs: {
            android: "https://cdn.app.com/package/app20190501.apk",
            ios: "https://itunes.apple.com/cn/app/appid123?mt=8",
            yyb: "http://a.app.qq.com/o/simple.jsp?pkgname=com.app.www&ckey=CK123",
          },
        },
        (s, d, url) => {
          alert("====");
          console.log("callbackout", s, d, url);
          s != 1 && copy(url);
          return 2;
        }
      );

**Comment by jawidx** [comment]
需要确认走到scheme方案中（scheme才有回调），同时确认端上有调用回调方法
