### ISSUE TITLE
是否支持deeplink的跳转？

### ISSUE THREAD

**Issue by PeiTianHuang** [jawidx/web-launch-app#5]
文档中的示例：
lanchApp.open({ // 参数含义参见Api部分
    scheme: 'app://path?k=v',
    url: 'https://link.domain.com/path?k=v',
    param:{
        k2: 'v2'
    }
});

想问下大佬该插件是否支持deeplink的跳转，比如taobao://fans，因为目前已经不使用universal link了。url参数如果我直接填写deeplink，则app未安装时safari会出现弹窗提示链接无效。

**Comment by jawidx** [comment]
请参考api文档（scheme参数内容就是deeplink，url参数内容是universallink或applink），未安装app时使用scheme唤起safari提示链接无效是正常的，所以建议ios上使用ulink，微信7.0.5也已经支持ulink了
