### ISSUE TITLE
请问，从浏览器访问跳转，就是web端去处理吗？

### ISSUE THREAD

**Issue by wangirving** [jawidx/web-launch-app#7]
安卓端配置好路径就可以了吗？短信短链接访问浏览器跳转app的逻辑是web端处理？我这边chrome可以跳转，三星自带浏览器也可以，小米华为自带浏览器就不行了，是web代码的问题吗？

**Comment by jawidx** [comment]
android的applink在各种环境中支持情况不一样（主要是chrome，还有三星、小米旧版本、其它基于chrome的浏览器），，实现上就是端做支持，配置适配的path
