### ISSUE TITLE
请问有详细的用法吗

### ISSUE THREAD

**Issue by hearsay316** [jawidx/web-launch-app#8]
你好。  有没有详细的例子？  比如直接运行，手机能打开微信？  我直接es6 语言引用包，发现并不能运行。这个运行环境是什么？

**Comment by hearsay316** [comment]
不好意思,用的是谷歌浏览器,原来谷歌浏览器不支持自动加载app,https://developer.chrome.com/multidevice/android/intents ,
![image](https://user-images.githubusercontent.com/10139810/64581427-a9f18180-d3bc-11e9-8291-90d92c6b9540.png)
很受伤

**Comment by jawidx** [comment]
1.chrome文档很清楚说的是『不支持直接url输入或无用户手势情况下intenturl』，所以用户点击时发scheme请求是没问题的
2.例子参考文档中demo即可，或真下源码后执行npm i，npm run build, npm run start，运行examples中代码看效果
3.如果自己app未做支持，可以用好看视频的scheme：baiduhaokan://home/index
